In [3]:
import pandas as pd
import numpy as np

In [4]:
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
sns.set(style="whitegrid")

In [5]:
%matplotlib inline

In [6]:
from sklearn.preprocessing import LabelEncoder

In [7]:
import sys
!{sys.executable} -m pip install category_encoders
from category_encoders import HashingEncoder

Requirement already satisfied: category_encoders in C:\Users\ukohn\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (2.9.0)
Requirement already satisfied: numpy>=1.14.0 in C:\Users\ukohn\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from category_encoders) (2.4.2)
Requirement already satisfied: pandas>=1.0.5 in C:\Users\ukohn\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from category_encoders) (3.0.1)
Requirement already satisfied: patsy>=0.5.1 in C:\Users\ukohn\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from category_encoders) (1.0.2)
Requirement already satisfied: scikit-learn>=1.6.0 in C:\Users\ukohn\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from category_encoders) (1.8.0)
Requirement already satisfied: scipy>=1.0.0 in C:\Users\ukohn\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from category_encoders) (1.17.1)
Requirement already satisfied: statsmodels>=0.9.0 in C:\Users\ukohn\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from category_encoders) (0.14.6)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\ukohn\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas>=1.0.5->category_encoders) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\ukohn\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas>=1.0.5->category_encoders) (2025.3)
Requirement already satisfied: six>=1.5 in C:\Users\ukohn\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.0.5->category_encoders) (1.17.0)
Requirement already satisfied: joblib>=1.3.0 in C:\Users\ukohn\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from scikit-learn>=1.6.0->category_encoders) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in C:\Users\ukohn\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from scikit-learn>=1.6.0->category_encoders) (3.6.0)
Requirement already satisfied: packaging>=21.3 in C:\Users\ukohn\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from statsmodels>=0.9.0->category_encoders) (26.0)

In [8]:
train_df = pd.read_csv('E:/ДушитьУдава/ML-P-/notebooks/hw2forDATASET/titanic/train.csv')
test_df = pd.read_csv('E:/ДушитьУдава/ML-P-/notebooks/hw2forDATASET/titanic/test.csv')
gender_submission_df = pd.read_csv('E:/ДушитьУдава/ML-P-/notebooks/hw2forDATASET/titanic/gender_submission.csv')

In [9]:
# Посмотреть первые и последние строки
train_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [10]:
train_df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [15]:
train_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [17]:
train_df.shape

(891, 12)

In [18]:
# Общая информация о колонках, типах и пропусках
train_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [34]:
# Статистика по числовым колонкам
train_df.describe()
train_df.describe(include="string")

                           Name   Sex  Ticket Cabin Embarked
count                       891   891     891   204      889
unique                      891     2     681   147        3
top     Braund, Mr. Owen Harris  male  347082    G6        S
freq                          1   577       7     4      644

In [35]:
# Пропуски
train_df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [36]:
#Дубликаты
train_df.duplicated().sum()

np.int64(0)

In [43]:
#Две пропущенные в embarked и очень много в cabin
train_df[['Sex', 'Embarked', 'Cabin']].isnull().sum()

Sex           0
Embarked      2
Cabin       687
dtype: int64

In [44]:
mode_embarked = train_df['Embarked'].mode()[0]#мода
train_df['Embarked'].fillna(mode_embarked, inplace=True)#заполняем

C:\Users\ukohn\AppData\Local\Temp\ipykernel_20004\1101099280.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  train_df['Embarked'].fillna(mode_embarked, inplace=True)#заполняем

0      S
1      C
2      S
3      S
4      S
      ..
886    S
887    S
888    S
889    C
890    Q
Name: Embarked, Length: 891, dtype: str

In [45]:
train_df['Embarked'].isnull().sum()

np.int64(2)

In [2]:
# Age медиана, чтобы не была чувствительна к выбросам при сильном разбросе данных (возраста)
train_df['Age'].fillna(train_df['Age'].median(), inplace=True)
# Embarked мода, тк не может быть промежуточного. Только определенные категории
train_df['Embarked'].fillna(train_df['Embarked'].mode()[0], inplace=True)
# Cabin удаляем, потому что если модель начнет предсказывать имея малое количество данных, то скорее всего она ошибётся
train_df.dropna(columns=['Cabin'], inplace=True)

NameError: name 'train_df' is not defined